# Generated by Django 2.2.6 on 2020-01-30 06:04

from django.db import migrations, models
import vendor_process.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(default=vendor_process.models.increment_vendor_number, editable=False, max_length=20)),
                ('account_id', models.IntegerField(blank=True, default=None, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('vendor_type', models.CharField(max_length=25)),
                ('company_door_street', models.CharField(max_length=100)),
                ('company_locality', models.CharField(max_length=50)),
                ('company_state', models.CharField(max_length=50)),
                ('company_pincode', models.IntegerField()),
                ('company_email', models.EmailField(max_length=254)),
                ('proprietorDirectorName', models.CharField(max_length=100)),
                ('proprietorDirectorContact', models.BigIntegerField()),
                ('local_contact_name', models.CharField(max_length=100)),
                ('local_contact_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('gstin', models.CharField(max_length=10)),
                ('uin', models.CharField(max_length=10)),
                ('pan', models.CharField(max_length=10)),
                ('account_no', models.BigIntegerField()),
                ('account_name', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('insurance_no', models.CharField(max_length=30)),
                ('insurance_name', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(max_length=9, null=True)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
